# Generated by Django 5.2 on 2025-04-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_grocery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
